// examples/nextjs/app/page.tsx
import {
  commonloomAssetBasePath,
  commonloomDiagnostics,
  commonloomDocuments,
} from '../src/generated/commonloom-content';

const [compiledDocument] = commonloomDocuments;

export default function Home() {
  if (!compiledDocument) {
    return (
      <main className="commonloom-example">
        <section className="commonloom-shell">
          <h1>No Commonloom content generated.</h1>
        </section>
      </main>
    );
  }

  return (
    <main className="commonloom-example">
      <section className="commonloom-shell">
        <header className="commonloom-header">
          <div>
            <p className="commonloom-kicker">Next.js integration</p>
            <h1 className="commonloom-title">{compiledDocument.title}</h1>
            <p className="commonloom-summary">{compiledDocument.summary}</p>
          </div>
          <img
            className="commonloom-logo"
            src={`${commonloomAssetBasePath}/commonloom-logo-light-transparent.png`}
            alt="Commonloom logo"
          />
        </header>

        <div className="commonloom-grid">
          <article
            className="commonloom-card commonloom-rendered"
            dangerouslySetInnerHTML={{ __html: compiledDocument.bodyHtml }}
          />
          <aside className="commonloom-card commonloom-meta">
            <dl>
              <dt>Content hash</dt>
              <dd>{compiledDocument.trace.contentHash.slice(0, 12)}</dd>
              <dt>Headings</dt>
              <dd>{compiledDocument.trace.headings.length}</dd>
              <dt>Links</dt>
              <dd>{compiledDocument.trace.links.length}</dd>
              <dt>Diagnostics</dt>
              <dd>{commonloomDiagnostics.length}</dd>
            </dl>
          </aside>
        </div>
      </section>
    </main>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import {
  commonloomAssetBasePath,
  commonloomDiagnostics,
  commonloomDocuments,
} from './generated/commonloom-content';

const compiledDocument = commonloomDocuments[0];
</script>

<template>
  <main class="commonloom-example">
    <section v-if="compiledDocument" class="commonloom-shell">
      <header class="commonloom-header">
        <div>
          <p class="commonloom-kicker">Vue integration</p>
          <h1 class="commonloom-title">{{ compiledDocument.title }}</h1>
          <p class="commonloom-summary">{{ compiledDocument.summary }}</p>
        </div>
        <img
          class="commonloom-logo"
          :src="`${commonloomAssetBasePath}/commonloom-logo-light-transparent.png`"
          alt="Commonloom logo"
        />
      </header>

      <div class="commonloom-grid">
        <article
          class="commonloom-card commonloom-rendered"
          v-html="compiledDocument.bodyHtml"
        />
        <aside class="commonloom-card commonloom-meta">
          <dl>
            <dt>Content hash</dt>
            <dd>{{ compiledDocument.trace.contentHash.slice(0, 12) }}</dd>
            <dt>Headings</dt>
            <dd>{{ compiledDocument.trace.headings.length }}</dd>
            <dt>Links</dt>
            <dd>{{ compiledDocument.trace.links.length }}</dd>
            <dt>Diagnostics</dt>
            <dd>{{ commonloomDiagnostics.length }}</dd>
          </dl>
        </aside>
      </div>
    </section>
    <section v-else class="commonloom-shell">
      <h1>No Commonloom content generated.</h1>
    </section>
  </main>
</template>
